export const deviceActions = {
  CONNECTION_CHANGE: 'CONNECTION_CHANGE',
  RESET_DEVICE: 'RESET_DEVICE',
};

export const authActions = {
  AUTH_LOGIN_PAYLOAD: 'AUTH_LOGIN_PAYLOAD',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};
